amc/urls.py
from django.conf.urls import url

from . import views

app_name = 'amc'

urlpatterns = [
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/printchallenge', views.print_challenge_sheets_grade,
        name='challengesheetsgrade'),
url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/printtest', views.print_test_sheets_grade,
        name='testsheetsgrade'),
    # /16-17/2nd/Trost/input
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/input$',
        views.input_amc_scores, name='inputamcscores'),
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/cba/(?P<test_type>[a-z0-9\-]+)',
        views.print_cba_test_sheets_class, name='cbasheetsclass'),
    # /16-17/2nd/Trost
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list,
        name='classlist'),
    # /16-17
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/printchallenge$',
        views.print_challenge_sheets_class,
        name='challengesheetsclass'),
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/printtest$',
        views.print_test_sheets_class,
        name='testsheetsclass'),

    # url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/addition',
    #     views.print_cba_test_sheets_class,
    #     name='cbasheetsclass'),

    # url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/print$', views.print_challenge_sheets_grade,
    #     name='challengesheetsgrade'),

    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/?$', views.school_roster, name='schoolroster'),
    url(r'^$', views.school_roster, name='schoolroster'),
]

brain/urls.py
from django.conf.urls import url

from . import views

app_name = 'brain'

urlpatterns = [
    #url(r'^(?i)doctest/?$', views.generate_ixl_pdf, name='doctest'),
    #url(r'^(?i)printpdf/?$', views.print_pdf, name='printpdf'),
    # /16-17/    school roster
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/?$', views.school_roster, name='schoolroster'),
    # /16-17/2nd/   Grade List
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/?$', views.grade_list, name='gradelist'),
    # /16-17/2nd/trost/   Class List
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list, name='classlist'),
    # /student/83   Student Detail
    url(r'^(?i)student/(?P<studentid>[0-9]+)/?$', views.student_detail, name='studentdetail'),


# Portal URLS
    url(r'^(?i)portal/?$', views.portal_school, name='portalschool'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.portal_class, name='portalclass'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/pass/(?P<studentid>[0-9]+)/?$', views.password,
        name='password'),

    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/(?P<studentid>[0-9]+)/?$', views.portal_student, name='portalstudent'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/groups/?$', views.make_groups, name='makegroups'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/morning/?$', views.morning_message, name='morningmessage'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/random/?$', views.random_student,
        name='randomstudent'),
    url(r'^$', views.index, name='index'),]

brain/forms.py
from django import forms
from .models import MorningMessage

class PasswordForm(forms.Form):
    password = forms.CharField(label='Your password', max_length=10,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'autofocus':'autofocus',
                                                                 'size': '6'}),)

class MorningMessageForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': 10, 'rows': 2}))
    class Meta:
        model = MorningMessage
        fields = ['date', 'message']

brain/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
import random
from datetime import date, timedelta, datetime, timezone
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib import messages

from .models import StudentRoster, Teacher, CurrentClass, AccountInfo, MorningMessage, MorningMessageSettings, Schedule
from amc.models import AMCTestResult
from ixl.models import IXLSkillScores, IXLStats, Challenge, ChallengeAssignment, ChallengeExercise, IXLSkill
from libs.functions import nwea_recommended_skills_list, class_skills_list
from brain.models import ReadingStats
from .forms import PasswordForm
from videos.models import Video
from badges.models import Sticker, StickerAssignment, Avatar
from brain.forms import MorningMessageForm
from brain.templatetags.brain_extras import challenges_completed
from .models import DataUpdate
from variables import *


def school_roster(request, year="16-17"):
    # url: /brain/16-17
    student_list = StudentRoster.objects.filter(
        current_class__year=year)  # .order_by('current_class__grade')#.order_by('current_class__teacher__last_name').order_by('current_class__studentroster__last_name')
    return render(request, 'brain/year_list.html', {'student_list': student_list, 'year': year, })


def grade_list(request, year="16-17", grade="2nd"):  # List of the full student roster
    # url: /brain/16-17/2nd/
    student_list = StudentRoster.objects.filter(current_class__grade=grade).filter(current_class__year=year)
    return render(request, 'brain/grade_list.html', {'student_list': student_list, 'year': year, 'grade': grade, })


def class_list(request, year="16-17", grade="2nd", teacher="Trost"):
    # url: /brain/16-17/2nd/trost
    teacher_object = Teacher.objects.get(last_name=teacher)

    current_date = date.today() - timedelta(hours=5)
    student_list = StudentRoster.objects.filter(current_class__grade=grade) \
        .filter(current_class__year=year).filter(current_class__teacher__last_name=teacher)

    ## Start Reading Statistics ##
    reading_list = ReadingStats.objects.filter(student__current_class__teacher=teacher_object).order_by(
        'student__last_name')

    total_starting_lexile, total_current_lexile, total_lexile_progress, total_myon_time_spent, total_lexile_goal = 0, 0, 0, 0, 0
    for item in reading_list:
        total_starting_lexile += item.starting_lexile
        total_current_lexile += item.current_lexile
        total_lexile_progress += item.lexile_progress
        total_lexile_goal += item.goal_lexile
        total_myon_time_spent += item.myon_time_spent

    classsize = len(reading_list)
    reading_averages = [round(total_starting_lexile / classsize), round(total_current_lexile / classsize),
                        round(total_lexile_progress / classsize), round(total_lexile_goal / classsize),
                        round(total_myon_time_spent / classsize)]

    ixl_priority = IXLStats.objects.filter(student__current_class__teacher=teacher_object).order_by('time_spent')
    myon_priority = reading_list.order_by('myon_time_spent')

    ## End Reading Statistics

    ## Start IXL Challenge ##
    challenge_list = []
    for student in student_list:
        challenge = ChallengeAssignment.objects.filter(student_id=student).latest('date_assigned')
        progress = challenge.completed()
        challenge_list.append((challenge, progress))

    ## End IXL Challenge ##

    ##-------------------------START CBA GRID-----------------------##


    spring_cba_student_grid = []
    for student in student_list:
        studentname = "{} {}.".format(student.first_name, student.last_name[0])
        ixl_score_list = [studentname, ]
        for i in range(20):  # Go through each exercise and get the score
            if spring_cba_ixl_match[i] != None:
                try:
                    score = IXLSkillScores.objects.get(student_id=student,
                                                       ixl_skill_id__skill_id=spring_cba_ixl_match[i])
                    score = score.score
                except:
                    score = 0
            else:
                score = None
            ixl_score_list.append(score)  # Append the score on the score list
        spring_cba_student_grid.append(ixl_score_list)  # when all done, append the score list and go to next student
    last_cba_row = ["IXL:"]
    for i in spring_cba_ixl_match:
        last_cba_row.append(i)

    #last_cba_row = [("IXL:",), spring_cba_ixl_match]
    #last_cba_row.insert(0, "IXL:")
    spring_cba_student_grid.append(last_cba_row)

    ##-------------------------END CBA GRID-----------------------##

    last_updated = DataUpdate.objects.first()

    return render(request, 'brain/class_list.html', {'student_list': student_list, 'year': year, 'grade': grade,
                                                     'teacher': teacher, 'teacher_object': teacher_object,
                                                     'reading_list': reading_list,
                                                     'challenge_list': challenge_list,
                                                     'reading_averages': reading_averages, 'ixl_priority': ixl_priority,
                                                     'myon_priority': myon_priority,
                                                     'spring_cba_student_grid': spring_cba_student_grid,
                                                     'spring_cba_descriptions': spring_cba_descriptions,
                                                     'spring_cba_ixl_match': spring_cba_ixl_match,
                                                     'last_updated':last_updated

                                                     })


def student_detail(request, studentid, ):  # Look at a single student's record
    # url: /student/83
    amc_tests = AMCTestResult.objects.all().filter(student_id=studentid)[:5]
    ixl_scores = IXLSkillScores.objects.all().filter(student_id=studentid)
    student = get_object_or_404(StudentRoster, student_id=studentid)
    actual_nwea_scores, estimated_nwea_scores, recommended_skill_list, subdomain_percentage_complete = nwea_recommended_skills_list(
        student, "all")
    return render(request, 'brain/student_detail.html', {'student': student, 'amc_tests': amc_tests,
                                                         'ixl_scores': ixl_scores,
                                                         "actual_nwea_scores": actual_nwea_scores,
                                                         "estimated_nwea_scores": estimated_nwea_scores,
                                                         "recommended_skill_list": recommended_skill_list,
                                                         "subdomain_percentage_complete": subdomain_percentage_complete})


def index(request):
    return render(request, 'brain/index.html', )


def portal_school(request):  # Portal that lists all the teachers in the school
    class_list = CurrentClass.objects.filter(year="16-17").order_by('teacher', )
    school_ixl_time_spent = IXLStats.objects.all().order_by('-time_spent')[:10]
    reading_stats = ReadingStats.objects.all()
    school_myon_time_spent = reading_stats.order_by('-myon_time_spent')[:10]
    school_myon_lexile_progress = reading_stats.order_by('-lexile_progress').exclude(lexile_progress__isnull=True)[:10]

    return render(request, 'brain/portal_school.html', {'class_list': class_list, 'color_list': COLORS,
                                                        'icon_list': ICONS, 'school_ixl_time_spent':
                                                            school_ixl_time_spent,
                                                        'school_myon_time_spent': school_myon_time_spent,
                                                        'school_myon_lexile_progress': school_myon_lexile_progress, })


def portal_class(request, teacher="Trost", grade="2nd"):  # Portal that lists all the students in that class
    student_list = StudentRoster.objects.filter(current_class__grade=grade) \
        .filter(current_class__year="16-17").filter(current_class__teacher__last_name=teacher).order_by('first_name')
    teacher = Teacher.objects.get(last_name=teacher)
    # Sort the student list by their number of IXL minutes spent [:5]
    class_ixl_time_spent = IXLStats.objects.filter(student__current_class__teacher=teacher).order_by('-time_spent')[:5]
    class_ixl_questions_answered = IXLStats.objects.filter(student__current_class__teacher=teacher).order_by(
        '-questions_answered')[:5]
    reading_stats = ReadingStats.objects.all()
    class_myon_time_spent = reading_stats.filter(student__current_class__teacher=teacher).order_by(
        '-myon_time_spent')
    for x in range(len(class_myon_time_spent)):
        if not class_myon_time_spent[x].myon_time_spent:
            class_myon_time_spent[x].myon_time_spent = 0
    class_myon_lexile_progress = reading_stats.filter(student__current_class__teacher=teacher).order_by(
        '-lexile_progress').exclude(lexile_progress__isnull=True)[:5]
    class_myon_time_spent = class_myon_time_spent[:5]
    # class_myon_books_read = class_myon_books_read[:5]
    leaderboardteachers = ['Trost', 'Cyphers', 'Mackinnon', 'DaSilva', "Berrie", "Stein", 'Garrett', 'Stella', ]
    myon_leaderboardteachers = ['Trost', 'Cyphers', 'Berrie', 'Mackinnon', 'Stein', "DaSilva", "Stella"]
    avatar_list = []
    if grade == "2nd":
        for student in student_list:
            try:
                current_avatar = Avatar.objects.filter(student=student).latest('date_selected')
                avatar_list.append(current_avatar.sticker.image)
            except:
                avatar_list.append('static/images/stickers/blanksticker.png')

    if teacher.last_name in leaderboardteachers:
        leaderboard_display = True
    else:

templates/brain/classes_nav.html
{% for teacher in teachers %}
    <li><a href="{% url 'brain:classlist' '16-17' '2nd' teacher.last_name %}">{{ teacher.last_name }}</a></li>
{% endfor %}

templates/brain/index.html
{% extends "brain/layout.html" %}

{% block title %}Home{% endblock title %}


{% block content %}
    <div class="grid-container">
<div class="hero-section">
  <div class="hero-section-text">
    <h1>Newton</h1>
    <h5>Select a class from above to get started</h5>
  </div>
</div>

    </div>



{% endblock content %}

templates/brain/ixl_frame.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IXL Frame</title>
</head>
<body>
IXL
</body>
</html>

templates/brain/layout.html
<!doctype html>
{% load static from staticfiles %}
{% load brain_extras %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} | Newton</title>
        <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
            <link rel="stylesheet" href="{% static 'css/app.css' %}">

        <link rel="stylesheet" href="{% static 'css/newton.css' %}">
{#        <link rel="stylesheet" href="{% static 'css/newton.scss' %}">#}
        <link href="https://fonts.googleapis.com/css?family=Roboto:700" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}">

        {% block css %}{% endblock %}
{#        <script src="{% static 'js/vendor/modernizr.js' %}"></script>#}
{#        <meta class="foundation-mq">#}
    </head>
    <body>
    {% if user.is_authenticated %}

        <nav class="top-bar" role="navigation">
        <div class="grid-container-padded">
        <ul class="menu menu-hover-lines">
                <li><a href="{% url 'brain:index' %}">
                        <img style="width: 80%;" src="{% static 'images/newtonlogoblue.png' %}">
                        </a></li>
  <li class="active"><a href="{% url 'brain:index' %}">Home</a></li>
  <li><a href="/classes/17-18/2nd/McPherson">McPherson</a></li>
  <li><a href="/classes/17-18/2nd/Palermo">Palermo</a></li>
  <li><a href="/classes/17-18/2nd/Ryan">Ryan</a></li>
  <li><a href="/classes/17-18/2nd/Trost">Trost</a></li>
  <li><a href="/admin">Admin</a></li>
</ul>
</div>

        </nav>
        {% if messages %}
            <div class="grid-x grid-padding-x">
                <div class="small-6 small-centered cell">
                    {% for message in messages %}
                        <div data-alert class="alert-box {{ message.tags }} radius">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="grid-x grid-padding-x">
        <div class="large-12 cell">
        {% block breadcrumbs %}{% endblock %}
            {% block heading %}{% endblock %}
            <hr><br>
        {% block content %}{% endblock %}
        </div>
        </div>


            <footer class="footer">
  <div class="grid-x grid-padding-x">
    <div class="small-12 cell">
{#      <p class="slogan">Newton</p>#}
{#      <p class="links">#}
{#        <a href="#">Home</a>#}
{#        <a href="#">Classes</a>#}
{#        <a href="#">AMC</a>#}
{#        <a href="#">NWEA</a>#}
{#        <a href="#">CBA</a>#}
{#        <a href="#">ENI</a>#}
{#        <a href="#">IXL</a>#}
{#        <a href="#">Admin</a>#}
{#      </p>#}

                <p class="quote">"If I have seen further than others, it is by standing upon the shoulders of giants."</p>
                <cite>Isaac Newton</cite>

      <p class="copyright">Copyright  © 2016-17</p>
    </div>
  </div>
</footer>
        {% else %}
        <h1 style="text-align: center; ">Hi, I'm Newton!</h1>
    <h1 style="text-align: center; ">Please <a href="/admin">login</a>, and we'll get started!</h1>
    {% endif %}

     <script src={% static 'js/vendor/jquery.js' %}></script>
    <script src={% static 'js/vendor/what-input.js' %}></script>
    <script src={% static 'js/vendor/foundation.js' %}></script>
    <script src={% static 'js/app.js' %}></script>
        {% block javascript %}{% endblock %}
        <script>
    $(document).foundation();
  </script>
    </body>
</html>

templates/brain/make_groups.html
{% extends "brain/portal_layout.html" %}
{% load brain_extras %}
{% block title %}{{ teacher.title }} {{ teacher.last_name }} | BTWA Portal {% endblock title %}
{% block heading %}
<h1>{{ teacher.title }} {{ teacher.last_name }}'s Autogroups!</h1>
{% endblock heading %}
{% block content %}
    <div class="row small-up-2 medium-up-2 large-up-2">
    {% for partner in partner_list %}
  <div class="column">
    <a class="button" style="background-color: {{ color_list|index:forloop.counter0 }}">
        <h5> {{ partner }} </h5>

    </a>
  </div>
    {% endfor %}
</div>

{% endblock content %}

templates/brain/password.html
{% extends "brain/portal_layout.html" %}
{% load brain_extras %}
{% block extrahead %}
{% endblock %}
{% block title %}{{ student.first_name }} | BTWA Portal {% endblock title %}
{% block heading %}
    <h1 style=" margin-bottom: -.5rem; margin-top:.3rem;text-align: center">{{ student.first_name }} {{ student.last_name.0 }}.</h1>
    <h1 style=" margin-bottom: -.5rem; margin-top:.3rem;text-align: center">What's your password?</h1>
    <h5 style="text-align: center"><a  href="{% url 'brain:portalclass' grade teacher.last_name %}"><i class="fa fa-arrow-circle-left"></i> I'm
        not {{ student.first_name }}</a></h5>

{% endblock heading %}
{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row">
  <div class="small-3 large-4 columns"><br></div>
  <div class="small-6 large-4 columns"><form action="" method="post">
{% csrf_token %}
   {{ form }}
      <input type="submit" value="Go!" class="large expanded button"/>
  </div>
  <div class="small-3 large-4 columns"><br></div>
</div>


</form>
{% endblock %}

templates/brain/portal_layout.html
<!doctype html>
{% load static from staticfiles %}
{% load brain_extras %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} | Newton</title>
        <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
            <link rel="stylesheet" href="{% static 'css/app.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Asap:700" rel="stylesheet">
    <script src="https://use.fontawesome.com/b215f0aabc.js"></script>
    <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}">

        {% block css %}{% endblock %}
{#        <script src="{% static 'js/vendor/modernizr.js' %}"></script>#}
{#        <meta class="foundation-mq">#}
    {% block extrahead %}{% endblock %}
            <link rel="stylesheet" href="{% static 'css/newton_portal.css' %}">

    </head>
    <body>


        <div class="row">
        <div class="large-12 columns">
        {% block breadcrumbs %}{% endblock %}
            {% block heading %}{% endblock %}
        {% if messages %}
            <div class="row">
                <div class="small-6 small-centered columns">
                    {% for message in messages %}
                        <div class="callout {{ message.tags }}" data-closable>
                            {{ message }}
                            <button type="button" class="close-button" aria-label="Dismiss message">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% block content %}{% endblock %}
        </div>
        </div>

     <script src={% static 'js/vendor/jquery.js' %}></script>
    <script src={% static 'js/vendor/what-input.js' %}></script>
    <script src={% static 'js/vendor/foundation.js' %}></script>
    <script src={% static 'js/app.js' %}></script>
        {% block javascript %}{% endblock %}
        <script>
    $(document).foundation();
  </script>
    </body>
</html>

templates/brain/portal_school.html
{% extends "brain/portal_layout.html" %}
{% load brain_extras %}
{% block title %}BTWA Portal {% endblock title %}
{% block heading %}
      <div class="grid-container">

    <img style="width: 75px;float: left;" src="/static/images/btwalogo.jpeg">
    <h1 style="position:relative;left: 15px;margin-bottom: -0.5rem">Booker T. Washington Academy</h1>
    <br>
      </div>
{% endblock heading %}
{% block content %}
        <div class="grid-container">

    <div class="callout success">
        <h5 style="text-align: center">Click on your teacher's name.</h5>
    </div>
    <div class="grid-x grid-margin-x">
        {% for class in class_list %}
            <div class="medium-4 large-3 cell">
                <a class="expanded button" style="background-color: {{ color_list|index:forloop.counter0 }}"
                   href="{% url 'brain:portalclass' class.grade class.teacher.last_name %}"><h4><i
                        class="fa {{ icon_list|index:forloop.counter0 }}"></i>
                    {{ class.teacher.last_name }} </h4></a>
            </div>
        {% endfor %}
    </div>
<hr>

    <h3 style="color: #0c4d78;text-align: center"><i class="fa fa-star"></i> School Leaderboards <i class="fa fa-star"></i></h3>

    <div class="grid-x grid-margin-x">
        <div class="cell small-4 callout warning">
    <h4 style="text-align: center; color: #e15258"><i class="fa fa-clock-o"></i> IXL Time Spent <i class="fa fa-clock-o"></i></h4>
    {% for student in school_ixl_time_spent %}
    <h5 style="color: {{ color_list|index:forloop.counter0 }}">{{ forloop.counter }}. {{ student.student.first_name }} {{ student.student.last_name.0 }}: {{ student.time_spent }} mins</h5>
    {% endfor %}
    </div>

            <div class="cell small-4 callout warning">
    <h4 style="text-align: center; color: #51b72f"><i class="fa fa-clock-o"></i> myON Time Spent <i class="fa fa-clock-o"></i></h4>
    {% for student in school_myon_time_spent %}
    <h5 style="color: {{ color_list|index:forloop.counter0 }}">{{ forloop.counter }}. {{ student.student.first_name }} {{ student.student.last_name.0 }}: {{ student.myon_time_spent }} mins</h5>
    {% endfor %}
    </div>
        <div class="cell small-4 callout warning">
    <h4 style="text-align: center; color: #2556a1"><i class="fa fa-arrow-circle-up"></i> Lexile Growth <i class="fa fa-arrow-circle-up"></i></h4>
    {% for student in school_myon_lexile_progress %}
    <h5 style="color: {{ color_list|index:forloop.counter0 }}">{{ forloop.counter }}. {{ student.student.first_name }} {{ student.student.last_name.0 }}.</h5>
    {% endfor %}
{#    </div>#}
    </div>
        </div>
{% endblock content %}

templates/brain/random_student.html
{% extends "brain/portal_layout.html" %}

{% block title %}Random Student | {{ teacher }} {% endblock title %}
{% block heading %}

<style media="screen" type="text/css">

.hit-the-floor {
color: #fff;
font-size: 12em;
font-weight: bold;
font-family: Helvetica;
text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,.1), 0 0 5px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.3), 0 3px 5px rgba(0,0,0,.2), 0 5px 10px rgba(0,0,0,.25), 0 10px 10px rgba(0,0,0,.2), 0 20px 20px rgba(0,0,0,.15);
}

.hit-the-floor {
  text-align: center;
}

body {
  background-color: {{ color }};
}</style>


{% endblock heading %}
{% block content %}


    <div class="row">
   <div class="hit-the-floor">{{student.first_name}}</div>
    </div>


{% endblock content %}

templates/brain/year_list.html
{% extends "brain/layout.html" %}

{% block title %}{{ year }} Student List{% endblock title %}


{% block heading %}
<h1>{{ year }} Student List</h1>
{% endblock heading %}

{% block content %}
 {{ student_list.count }} students
<table style="width:80%; border: 1px solid black;">
<tr>
<th width="200">Student</th>
<th width="100">Grade </th>
<th width="150">Teacher</th>

</tr>
{% for student in student_list %}
    <tr>
    <td><a href="{% url 'brain:studentdetail' student.student_id %}">{{ student.first_name }} {{  student.last_name  }}</a></td>
    <td><a href="{% url 'brain:gradelist' year student.current_class.grade %}">{{ student.current_class.grade }}</a></td>
    <td><a href="{% url 'brain:classlist' year student.current_class.grade student.current_class.teacher.last_name %}">{{ student.current_class.teacher.last_name }}</a></td>
  </tr>
{% endfor %}
</table>

{% endblock content %}