amc/urls.py
from django.conf.urls import url

from . import views

app_name = 'amc'

urlpatterns = [
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/printchallenge', views.print_challenge_sheets_grade,
        name='challengesheetsgrade'),
url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/printtest', views.print_test_sheets_grade,
        name='testsheetsgrade'),
    # /16-17/2nd/Trost/input
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/input$',
        views.input_amc_scores, name='inputamcscores'),
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/cba/(?P<test_type>[a-z0-9\-]+)',
        views.print_cba_test_sheets_class, name='cbasheetsclass'),
    # /16-17/2nd/Trost
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list,
        name='classlist'),
    # /16-17
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/printchallenge$',
        views.print_challenge_sheets_class,
        name='challengesheetsclass'),
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/printtest$',
        views.print_test_sheets_class,
        name='testsheetsclass'),

    # url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/addition',
    #     views.print_cba_test_sheets_class,
    #     name='cbasheetsclass'),

    # url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/print$', views.print_challenge_sheets_grade,
    #     name='challengesheetsgrade'),

    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/?$', views.school_roster, name='schoolroster'),
    url(r'^$', views.school_roster, name='schoolroster'),
]

brain/urls.py
from django.conf.urls import url

from . import views

app_name = 'brain'

urlpatterns = [
    #url(r'^(?i)doctest/?$', views.generate_ixl_pdf, name='doctest'),
    #url(r'^(?i)printpdf/?$', views.print_pdf, name='printpdf'),
    # /16-17/    school roster
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/?$', views.school_roster, name='schoolroster'),
    # /16-17/2nd/   Grade List
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/?$', views.grade_list, name='gradelist'),
    # /16-17/2nd/trost/   Class List
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list, name='classlist'),
    # /student/83   Student Detail
    url(r'^(?i)student/(?P<studentid>[0-9]+)/?$', views.student_detail, name='studentdetail'),


# Portal URLS
    url(r'^(?i)portal/?$', views.portal_school, name='portalschool'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.portal_class, name='portalclass'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/pass/(?P<studentid>[0-9]+)/?$', views.password,
        name='password'),

    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/(?P<studentid>[0-9]+)/?$', views.portal_student, name='portalstudent'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/groups/?$', views.make_groups, name='makegroups'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/morning/?$', views.morning_message, name='morningmessage'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/random/?$', views.random_student,
        name='randomstudent'),
    url(r'^$', views.index, name='index'),]

amc/models.py
import datetime

from django.db import models

from brain.models import StudentRoster, CurrentClass
# Create your models here.


class AMCTest(models.Model):
    test_number = models.IntegerField(unique=True)
    topic = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=100, unique=True)
    grade_equivalent = models.CharField(max_length=100)
    total_questions = models.IntegerField(default=20)
    minimum_passing_grade = models.IntegerField(default=18)

    def __str__(self):
        return '%s -- %s' % (self.topic, self.name)

    class Meta:
        verbose_name = "AMC Test"
        verbose_name_plural = "AMC Tests"


class AMCTestResult(models.Model):
    student = models.ForeignKey(StudentRoster, blank=False, null=False)
    test = models.ForeignKey(AMCTest)
    score = models.IntegerField(blank=False, null=False)
    date_tested = models.DateField(default=datetime.date.today, verbose_name='Date Tested')

    def passing_score(self):
        if self.score >= self.test.minimum_passing_grade:
            return True
        elif self.score < self.test.minimum_passing_grade:
            return False
        else:
            raise ValueError

    passing_score.boolean = True
    passing_score.short_description = 'Pass?'


    def __str__(self):
        return '%s -- %s Pass: %s' % (self.student, self.test, self.passing_score(), )

    class Meta:
        verbose_name = "AMC Test Score"
        verbose_name_plural = "AMC Test Scores"
        ordering = ['-date_tested', 'student']
        unique_together = ("student", "test", "date_tested")


class AMCStartingTest(models.Model):
    student = models.ForeignKey(StudentRoster, blank=False, null=False)
    starting_test = models.IntegerField(verbose_name='Starting Test')

    class Meta:
        verbose_name = "AMC Starting Test"
        verbose_name_plural = "AMC Starting Tests"

amc/forms.py
from django import forms
from django.core import validators
from . import models


class InputAMCScores(forms.ModelForm):
    class Meta:
        model = models.AMCTestResult
        fields = [
            'student', 'test', 'date_tested', 'score',
        ]

amc/views.py
import datetime
import random

from django.core.urlresolvers import reverse
from django.shortcuts import render, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from . import forms
from brain.models import StudentRoster, CurrentClass
from brain.templatetags import brain_extras
from amc.models import AMCTestResult, AMCTest
from variables import *

def school_roster(request, year="16-17"):
    # url: /brain/16-17
    student_list = StudentRoster.objects.filter(
        current_class__year=year)  # .order_by('current_class__grade')#.order_by('current_class__teacher__last_name').order_by('current_class__studentroster__last_name')
    teacher_list = CurrentClass.objects.filter(year=year)
    return render(request, 'amc/index.html',
                  {'student_list': student_list, 'year': year, 'teacher_list': teacher_list,})


def grade_list(request, year="16-17", grade="2nd"):  # List of the full student roster
    # url: /brain/16-17/2nd/
    student_list = StudentRoster.objects.filter(current_class__grade=grade).filter(current_class__year=year)
    return render(request, 'brain/grade_list.html', {'student_list': student_list, 'year': year, 'grade': grade,})


def class_list(request, year="16-17", grade="2nd", teacher="Trost"):
    # url: /brain/16-17/2nd/trost
    student_list = StudentRoster.objects.filter(current_class__grade=grade) \
        .filter(current_class__year=year).filter(current_class__teacher__last_name=teacher)
    amc_tests = AMCTestResult.objects.all()

    return render(request, 'amc/class_list.html', {'student_list': student_list, 'year': year, 'grade': grade,
                                                   'teacher': teacher, 'amc_tests': amc_tests})

# This one is for the Challenge Sheets - Flash Cards
def get_student_and_test_list_for_challenges(student_list):
    student_and_test_list = []
    for student in student_list:
        if student.first_name == "Stephen":
             continue
        elif brain_extras.amc_badges_earned(student) ==10:
            continue
        current_test_number = brain_extras.current_amc_test(
            student)  # Run script to figure out the current test for student
        current_test = AMCTest.objects.get(test_number=current_test_number)  # Get the current test
        current_test_name = current_test.name # Statue of Liberty
        current_test_signifier = current_test.topic # Keeps a string for "Addition 1" or "Subtraction 5" or "Fractions"
        current_test_topic = current_test.topic.replace(" ",
                                                        "").upper()  # Get the Topic (Addition 3) and turn it into ADDITION3
        if 'SUBTRACTION' in current_test_topic:  # This is for the Template so it knows if we're adding or subtracting
            test_type = 'SUB'
        elif "ADDITION" in current_test_topic:
            test_type = 'ADD'
        else:
            test_type = "IMAGE"  # This will be used for clocks, coins, etc.

        first_name = student.first_name  # Split these for ease of use down the line
        last_name = student.last_name
        # Now put all the information into the tuple and append the tuple to the list
        combinationset = TESTDICTIONARY[current_test_topic]
        # finallist order will go [(1,2), (1,3), (1,4)..., (1,9), 3, 4, 5... 10], [(2,2)...4]
        tempcombolist = []
        tempanswerlist = []
        finallist = []
        for combination in combinationset:
            # Get the first combination and add it to a short combo list
            var1, var2 = combination
            tempcombolist.append((var1, var2))
            # Add those two numbers together and add that to a short answer list
            if test_type == 'ADD':
                tempanswerlist.append(var1+var2)
            elif test_type == 'SUB':
                tempanswerlist.append(var1 - var2)
            elif test_type == 'IMAGE':
                tempanswerlist.append(var2)
            # Repeat until you have 10 items in both lists, then append those lists together into one list.
            if len(tempcombolist) == 10:
            # Then put that list as a new item at the end of the big list.
                tempanswerlist[0], tempanswerlist[1] = tempanswerlist[1], tempanswerlist[0]
                tempanswerlist[2], tempanswerlist[3] = tempanswerlist[3], tempanswerlist[2]
                tempanswerlist[4], tempanswerlist[5] = tempanswerlist[5], tempanswerlist[4]
                tempanswerlist[6], tempanswerlist[7] = tempanswerlist[7], tempanswerlist[6]
                tempanswerlist[8], tempanswerlist[9] = tempanswerlist[9], tempanswerlist[8]
                j = tempcombolist + tempanswerlist
                finallist.append(j)
                tempcombolist = []
                tempanswerlist = []
        if len(tempcombolist):
            while len(tempcombolist) != 10:
                tempcombolist.append('None')
                tempanswerlist.append('None')
            tempanswerlist[0], tempanswerlist[1] = tempanswerlist[1], tempanswerlist[0]
            tempanswerlist[2], tempanswerlist[3] = tempanswerlist[3], tempanswerlist[2]
            tempanswerlist[4], tempanswerlist[5] = tempanswerlist[5], tempanswerlist[4]
            tempanswerlist[6], tempanswerlist[7] = tempanswerlist[7], tempanswerlist[6]
            tempanswerlist[8], tempanswerlist[9] = tempanswerlist[9], tempanswerlist[8]
            j = tempcombolist + tempanswerlist
            finallist.append(j)
            tempcombolist = []
            tempanswerlist = []

        student_list_entry = (first_name, last_name, current_test_name, test_type,
                              finallist, current_test_signifier)

        student_and_test_list.append(student_list_entry)
    return student_and_test_list

# This one is for the Test Sheets
def get_student_and_test_list_for_tests(student_list):
    student_and_test_list = []
    for student in student_list:
        if student.first_name == "Stephen":
            continue
        elif brain_extras.amc_badges_earned(student) ==10:
            continue
        current_test_number = brain_extras.current_amc_test(
            student)  # Run script to figure out the current test for student
        current_test = AMCTest.objects.get(test_number=current_test_number)  # Get the current test
        current_test_name = current_test.name
        current_test_signifier = current_test.topic # Keeps a string for "Addition 1" or "Subtraction 5" or "Fractions"
        current_test_topic = current_test.topic.replace(" ",
                                                        "").upper()  # Get the Topic (Addition 3) and turn it into ADDITION3
        if 'SUBTRACTION' in current_test_topic:  # This is for the Template so it knows if we're adding or subtracting
            test_type = 'SUB'
        elif "ADDITION" in current_test_topic:
            test_type = 'ADD'
        else:
            test_type = "IMAGE"  # This will be used for clocks, coins, etc.

        first_name = student.first_name  # Split these for ease of use down the line
        last_name = student.last_name
        # Randomize Combinations and pull first 20 from list. If you run out of combos, loop around.
        problem_list = TESTDICTIONARY[current_test_topic]
        random.shuffle(problem_list)
        test_list = []
        for i in problem_list:
            test_list.append(i)
        if test_type == 'IMAGE':
            test_list = test_list[:9]
        else:
            test_list=test_list[:20]
            if len(test_list) < 20:
                n = 0
                while len(test_list) < 20:
                    test_list.append(test_list[n])
                    n += 1
        # Now put all the information into the tuple and append the tuple to the list
        student_list_entry = (first_name, last_name, current_test_name, test_type,
                              test_list, current_test_signifier)
        student_and_test_list.append(student_list_entry)
    return student_and_test_list

# This one is for the Test Sheets
def spring_cba_test(student_list, test_type):
    student_and_test_list = []
    for student in student_list:
        if test_type == "ADD":
            test_type = 'ADD'
            current_test_name = "CBA Addition Facts"

            problem_list = SPRINGADDITION
        elif test_type == 'SUB':
            current_test_name = "CBA Subtraction Facts"

            test_type = 'SUB'
            problem_list = SPRINGSUBTRACTION
        first_name = student.first_name  # Split these for ease of use down the line
        last_name = student.last_name
        # Randomize Combinations and pull first 20 from list. If you run out of combos, loop around.
        random.shuffle(problem_list)
        test_list = []
        for i in problem_list:
            test_list.append(i)
        test_list=test_list[:20]
        if len(test_list) < 20:
            n = 0
            while len(test_list) < 20:
                test_list.append(test_list[n])
                n += 1
        # Now put all the information into the tuple and append the tuple to the list
        student_list_entry = (first_name, last_name, current_test_name, test_type,
                              test_list)
        student_and_test_list.append(student_list_entry)
    return student_and_test_list


def print_challenge_sheets_class(request, year="16-17", grade="2nd", teacher="Trost"):
    student_list = StudentRoster.objects.filter(current_class__grade=grade) \
        .filter(current_class__year=year).filter(current_class__teacher__last_name=teacher)
    student_and_test_list = get_student_and_test_list_for_challenges(student_list)

    return render(request, 'amc/amc_card_print.html',
                  {'year': year, 'grade': grade, 'teacher': teacher, 'student_and_test_list': student_and_test_list})

templates/amc/amc_card_print.html
{% extends "amc/print_layout.html" %}
{% load brain_extras %}
{% load mathfilters %}
{% block title %}AMC Flash Cards{% endblock title %}
{% block content %}
    {% for student in student_and_test_list %}
        <div class="row" style="width: 218mm;height: 279mm">
            {% with student.0 as first_name %}
                {% with student.1 as last_name %}
                    {% with student.2 as challenge_name %}
                        {% with student.3 as list_type %}
                            {% with student.4 as combinations %}
{#      {{ first_name }} {{ last_name.0 }}                          #}
{#                                <img src="/static/images/amc-bnw.png" style="width: 120px; float: left; padding: 10px">#}
                                {% for page in combinations %}
                                    {% for combo in page %}
                                    <div style="padding:0px; width: 49%; height:20%; float: left;font-size: 1.1em; border-style: solid; border-width: 1px; border-color: #7d7d7d">
                                        {% if combo != 'None' %}
                                        {% if forloop.counter <= 10 %}

                                        {% if list_type == "ADD" %}
                                            {% if combo.0 == combo.1 %}

                                                <p class="question"> {{ combo.0 }} + {{ combo.1 }} =</p>
                                            {% else %}

                                                <p class="question">{{ combo.0 }} + {{ combo.1 }} = </p>

                                                <p class="question">{{ combo.1 }} + {{ combo.0 }} =</p>
                                            {% endif %}
                                        {% elif list_type == "SUB" %}
                                            <p class="question">{{ combo.0 }} - {{ combo.1 }} =</p>
                                        {% elif list_type == "IMAGE" %}
                                            <img style="height: 90%; margin:auto; display:block; padding-top: 5px;"  src="/static/images/time/{{ combo.0 }}.png">
                                        {% endif %}
                                            {% elif forloop.counter > 10 %}
<br>
                                            {% if list_type == "IMAGE" %}
                                              <p class="answer">{{combo}}</p>
                                                {% else %}
                                            <p class="answer">{{combo}}</p>
                                                {% endif %}
                                           <p  class="cardinfo">{{ first_name }} {{ last_name.0 }}.</p>
                                            <p class="cardinfo">{{ challenge_name }} - {% now "SHORT_DATE_FORMAT" %}</p>
                                        {% endif %}
                                    {% endif %}
                                        </div>
                                        {% if forloop.counter == 10 %}
{#                                            SEPARATE COMBINATIONS AND ANSWERS         #}
                                            <table class="page"></table>
        <table style="page-break-after: always;"></table>
                                                {% endif %}
                                        {% endfor %}
{#                                    SEPARATE THE PAGES AFTER THE ANSWERS   #}
                                      <table class="page"></table>
        <table style="page-break-after: always;"></table>
                                {% endfor %}
{#                                SEPARATE THE STUDENTS        #}
{#                                <table class="page"></table>#}
{#        <table style="page-break-after: always;"></table>#}
                            {% endwith %}
                        {% endwith %}
                    {% endwith %}
                {% endwith %}
            {% endwith %}
        </div>


    {% endfor %}
    {#    <body onload="window.print()">#}
{% endblock content %}

templates/amc/amc_challenge_print.html
{% extends "amc/print_layout.html" %}
{% load brain_extras %}
{% load mathfilters %}
{% block title %}AMC Challenge Sheets{% endblock title %}
{% block content %}
    {% for student in student_and_test_list %}
        <div class="row" style="width: 750px;">
            {% with student.0 as first_name %}
                {% with student.1 as last_name %}
                    {% with student.2 as challenge_name %}
                        {% with student.3 as list_type %}
                            {% with student.4 as combinations %}
                                <div>
                                    <img src="/static/images/amc-bnw.png"
                                         style="width: 120px; float: left; padding: 10px">

                                    <h3 style="position: relative; line-height: 1.1">{{ first_name }} {{ last_name.0 }}, you're doing
                                        The {{ challenge_name }} Challenge!</h3>
                                    <div><h6>Make a flashcard for each combination, then practice at home and school to
                                        get quick!</h6></div>
                                </div>
                                {% for combo in combinations %}
                                    <div style="padding:10px; width: 20%; float: left;padding-top: 15px;padding-bottom:15px;font-size: 1.1em; border-style: solid; border-width: 1px;">
                                        {% if list_type == "ADD" %}
                                            {% if combo.0 == combo.1 %}
                                                <i style="padding-right: 4px" class="fa fa-square-o"
                                                   aria-hidden="true"></i>
                                                {{ combo.0 }} + {{ combo.1 }} =
                                                {{ combo.0 |add:combo.1 }}
                                            {% else %}
                                                <i style="padding-right: 4px" class="fa fa-square-o"
                                                   aria-hidden="true"></i>
                                                {{ combo.0 }} + {{ combo.1 }} =
                                                {{ combo.0 |add:combo.1 }}
                                                </div>
                                                <div style="padding:10px; width: 20%; float: left;padding-top: 15px;padding-bottom:15px; ;font-size: 1.1em; border-style: solid; border-width: 1px;">

                                                <i style="padding-right: 4px" class="fa fa-square-o"
                                                   aria-hidden="true"></i>
                                                {{ combo.1 }} + {{ combo.0 }} =
                                                {{ combo.1 |add:combo.0 }}
                                            {% endif %}
                                        {% elif list_type == "SUB" %}
                                            <i style="padding-right: 4px" class="fa fa-square-o" aria-hidden="true"></i>
                                            {{ combo.0 }} - {{ combo.1 }} =
                                            {{ combo.0 |sub:combo.1 }}

                                        {% elif list_type == "IMAGE" %}
                                        {% endif %}
                                        </div>
                                {% endfor %}
                            {% endwith %}
                        {% endwith %}
                    {% endwith %}
                {% endwith %}
            {% endwith %}
        </div>
        <table class="page"></table>
        <table style="page-break-after: always;"></table>

    {% endfor %}
    {#    <body onload="window.print()">#}
{% endblock content %}

templates/amc/class_list.html
{% extends "brain/layout.html" %}
{% load brain_extras %}

{% block title %}{{ teacher }} AMC Student List{% endblock title %}

{% block heading %}
<h1>{{ teacher }} AMC Student List</h1>
{% endblock heading %}

{% block content %}
{% if student_list.count > 0 %}
        <div style="margin-top: -20px" class="row">

  <div class="large-6 columns"> <span style="font-size: 2.0rem;  font-family: 'Roboto', sans-serif;">Class Badges Earned:&nbsp</span>
      <span style="font-size: 2.0rem; font-family: 'Roboto', sans-serif;" class="success badge">{{ student_list|amc_teacher_badges_earned }}</span></div>

        <div class="large-6 columns">
         <a class="button" style="float:right; background-color: #37b32d;font-weight: bold " href="{% url 'amc:challengesheetsclass' year grade teacher %}">Print Challenges</a>
        <a class="button" style="float:right;font-weight: bold; background-color: #da3116" href="{% url 'amc:testsheetsclass' year grade teacher %}">Print Tests</a>
        <a class="button" style="float:right;font-weight: bold " href="{% url 'amc:inputamcscores' year grade teacher %}">Input Scores</a>

        </div>


</div>

                <div class="column row">

    {{ student_list.count }} student{{ student_list.count|pluralize }}

    <table>
<tr>
<th width="150">Student</th>
<th width="150">Current AMC</th>
<th width="50">Times Taken</th>
<th width="150">Grade Equivalent</th>
<th width="50">Badges Earned</th>

</tr>

{% for student in student_list %}{% with student|current_amc_test as curtest %}
    <tr>
    <td><a href="{% url 'brain:studentdetail' student.student_id %}">{{ student.first_name }} {{  student.last_name  }}</a></td>
    <td>{{student|current_amc_test|amc_number_to_text}}</td>
    <td>{{student|amc_number_of_test_attempts:curtest}}</td>
    <td>{{student|current_amc_test|amc_grade_equivalent}}</td>
    <td>{{ student|amc_badges_earned }}</td>
  </tr>         {% endwith %}

{% endfor %}
</table></div>
    {% else %}
    No students to show.
{% endif %}
</div></div>
{% endblock content %}

templates/amc/classes_nav.html
{% for teacher in teachers %}
    <li><a href="{% url 'amc:classlist' '16-17' '2nd' teacher.last_name %}">{{ teacher.last_name }}</a></li>
{% endfor %}

templates/amc/index.html
{% extends "brain/layout.html" %}
{% load brain_extras %}

{% block title %}
    {% if teacher %}
    {{ teacher }}'s AMC Tests
    {% elif grade %}
  {{ grade }} Grade AMC Tests
    {% elif year %}
    {{ year }} School-Wide AMC Tests
    {% endif %}
{% endblock title %}

{% block heading %}
    <h1>American Math Challenge</h1>
{% endblock heading %}

{% block content %}
            <div style="float:right;" class="large-6 columns">
        <a class="button" style="float:right;font-weight: bold; background-color: #da3116" href="{% url 'amc:testsheetsgrade' year '2nd' %}">Print Tests</a>
        <a class="button" style="float:right; background-color: #37b32d;font-weight: bold " href="{% url 'amc:challengesheetsgrade' year '2nd'  %}">Print Challenges</a>
        </div>

    <div class="row">
    <h4>Select a class to view.</h4>
{% for teacher in teacher_list %}
    <p><a class="large button" href="{% url 'amc:classlist' year teacher.grade teacher.teacher.last_name %}">{{ teacher.teacher }}</a>
   </p>
{% endfor %}
    </div>

{% endblock content %}

templates/amc/input_amc_scores_form.html
{% extends "brain/layout.html" %}
{% load brain_extras %}

{% block title %}Input {{ teacher }} AMC Tests{% endblock title %}
{% block heading %}
    <h1>Input {{ teacher }} AMC Tests</h1>
        <a href="{% url 'amc:classlist' year grade teacher %}">< Back to {{ teacher}}</a>

{% endblock heading %}

{% block content %}
    <div class="row">

        <form method="post">
            {{ formset.management_form }}

            <div class="small-11 small-centered columns">

                <table>
                    <tr>
                        <th width="50">Student</th>
                        <th width="50">Test</th>
                        <th width="20">Date Taken</th>
                        <th width="10">Score</th>
                    </tr>


                    {% for form in formset %}
                        <tr>
                            <td>
                                <a style="color: darkred">{{ form.non_field_errors }}</a>
                                {{ form.student.errors }}
                                {{ form.student }}
                            </td>

                            <td>
                                {{ form.test.errors }}
                                {{ form.test }}
                            </td>
                            <td>
                                {{ form.date_tested.errors }}
                                {{ form.date_tested }}
                            </td>
                            <td>
                                {{ form.score.errors }}
                                {{ form.score }}
                            </td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
            <hr>
            {% csrf_token %}
            <input type="submit" class="button" value="Save">

        </form>
    </div>

{% endblock content %}

templates/amc/print_layout.html
<!doctype html>
{% load static from staticfiles %}
{% load mathfilters %}
{% load brain_extras %}
<html class="no-js" lang="en">
    <head>
        <meta http-equiv="content-type"  charset="utf-8">
{#        <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
        <title>{% block title %}{% endblock %} | Newton</title>
{#        <link rel="stylesheet" href="{% static 'css/foundation.css' %}" media="screen">#}
        <link href="https://fonts.googleapis.com/css?family=Asap:700" rel="stylesheet">
    <script src="https://use.fontawesome.com/b215f0aabc.js"></script>
    <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}">

        {% block css %}{% endblock %}
        <script src="{% static 'js/vendor/modernizr.js' %}"></script>
        <meta class="foundation-mq">
    {% block extrahead %}{% endblock %}
            <link rel="stylesheet" href="{% static 'css/newton_portal.css' %}" media="all">
    <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}" media="print" />


    </head>
    <body>

        {% if messages %}
            <div class="row columns">
                <div class="small-6 small-centered columns">
                    {% for message in messages %}
                        <div data-alert class="alert-box {{ message.tags }} radius">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="row">
        <div class="large-12 columns">
        {% block breadcrumbs %}{% endblock %}
            {% block heading %}{% endblock %}
{#            <hr><br>#}
        {% block content %}{% endblock %}
        </div>
        </div>

        <script src="{% static 'js/vendor/jquery.js' %}"></script>
        <script src="{% static 'js/vendor/what-input.min.js' %}"></script>
        <script src="{% static 'js/foundation.js' %}"></script>
        {% block javascript %}{% endblock %}
        <script>
    $(document).foundation();
  </script>
    </body>
</html>