amc/urls.py
from django.conf.urls import url

from . import views

app_name = 'amc'

urlpatterns = [
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/printchallenge', views.print_challenge_sheets_grade,
        name='challengesheetsgrade'),
url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/printtest', views.print_test_sheets_grade,
        name='testsheetsgrade'),
    # /16-17/2nd/Trost/input
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/input$',
        views.input_amc_scores, name='inputamcscores'),
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/cba/(?P<test_type>[a-z0-9\-]+)',
        views.print_cba_test_sheets_class, name='cbasheetsclass'),
    # /16-17/2nd/Trost
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list,
        name='classlist'),
    # /16-17
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/printchallenge$',
        views.print_challenge_sheets_class,
        name='challengesheetsclass'),
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/printtest$',
        views.print_test_sheets_class,
        name='testsheetsclass'),

    # url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/addition',
    #     views.print_cba_test_sheets_class,
    #     name='cbasheetsclass'),

    # url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/print$', views.print_challenge_sheets_grade,
    #     name='challengesheetsgrade'),

    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/?$', views.school_roster, name='schoolroster'),
    url(r'^$', views.school_roster, name='schoolroster'),
]

brain/urls.py
from django.conf.urls import url

from . import views

app_name = 'brain'

urlpatterns = [
    #url(r'^(?i)doctest/?$', views.generate_ixl_pdf, name='doctest'),
    #url(r'^(?i)printpdf/?$', views.print_pdf, name='printpdf'),
    # /16-17/    school roster
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/?$', views.school_roster, name='schoolroster'),
    # /16-17/2nd/   Grade List
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/?$', views.grade_list, name='gradelist'),
    # /16-17/2nd/trost/   Class List
    url(r'^(?i)(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list, name='classlist'),
    # /student/83   Student Detail
    url(r'^(?i)student/(?P<studentid>[0-9]+)/?$', views.student_detail, name='studentdetail'),


# Portal URLS
    url(r'^(?i)portal/?$', views.portal_school, name='portalschool'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.portal_class, name='portalclass'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/pass/(?P<studentid>[0-9]+)/?$', views.password,
        name='password'),

    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/(?P<studentid>[0-9]+)/?$', views.portal_student, name='portalstudent'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/groups/?$', views.make_groups, name='makegroups'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/morning/?$', views.morning_message, name='morningmessage'),
    url(r'^(?i)portal/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/random/?$', views.random_student,
        name='randomstudent'),
    url(r'^$', views.index, name='index'),]

scoreit/urls.py
from django.conf.urls import url

from . import views

app_name = 'scoreit'

urlpatterns = [
    # /log/45
     url(r'(?i)log/(?P<student_id>[a-z0-9\-]+)$', views.class_list, name='classlist'),
    url(r'(?i)log/(?P<student_id>[a-z0-9\-]+)/(?P<subject>[a-z0-9\s]+)$', views.log_subject, name='logsubject'),
    url(r'(?i)gradeview/$', views.grade_view, name='gradeview'),
    url(r'(?i)gradeview/yesterday$', views.grade_view_yesterday, name='gradeviewyesterday'),
    url(r'(?i)gradeview/twodays', views.grade_view_twodays, name='gradeviewtwodays'),
    url(r'(?i)gradeview/threedays', views.grade_view_threedays, name='gradeviewthreedays'),

    # # /level/D
    # url(r'(?i)/level/(?P<level>\w)$', views.level_detail, name='leveldetail'),
    # # /16-17/2nd/Trost
    # url(r'^(?i)/(?P<year>[0-9]{2}-[0-9]{2})/(?P<grade>[a-z0-9]+)/(?P<teacher>[a-z0-9\-]+)/?$', views.class_list, name='classlist'),

]

scoreit/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from django.utils.timezone import now
# Create your models here.
from brain.models import Subject, StudentRoster, Teacher, CurrentClass

BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

class Score(models.Model):
    student = models.ForeignKey(StudentRoster)
    subject = models.ForeignKey(Subject)
    date = models.DateField(default=now, verbose_name="Date")
    hand = models.BooleanField(default=False, verbose_name="Raised Hand", choices=BOOL_CHOICES)
    slant = models.BooleanField(default=False, verbose_name="SLANT", choices=BOOL_CHOICES)
    transition = models.BooleanField(default=False, verbose_name="Transitions", choices=BOOL_CHOICES)
    please = models.BooleanField(default=False, verbose_name="Please/Thank You", choices=BOOL_CHOICES)
    instruction = models.BooleanField(default=False, verbose_name="Instructions 1st Time", choices=BOOL_CHOICES)
    material = models.BooleanField(default=False, verbose_name="Respected Materials", choices=BOOL_CHOICES)
    peer = models.BooleanField(default=False, verbose_name="Respected Peers", choices=BOOL_CHOICES)

    def get_absolute_url(self):
        return reverse('scoreit:classlist', kwargs={
            'student_id': self.student.student_id,
        })

    def __str__(self):
        return "{} {} {}".format(self.student, self.subject, self.date)


class TeacherApproval(models.Model):
    APPROVAL_CHOICES = (("YES","YES"),("NO","NO"))
    student = models.ForeignKey(StudentRoster)
    date = models.DateField(default=now, verbose_name='Date')
    approved = models.CharField(max_length=100, default="NO")

    class Meta:
        verbose_name = 'Teacher Approval'
        verbose_name_plural = 'Teacher Approvals'

scoreit/forms.py
from django import forms
from django.core import validators
from . import models


class ScoreForm(forms.ModelForm):
    class Meta:
        model = models.Score
        fields = ['hand', 'slant', 'transition', 'please', 'instruction', 'material', 'peer']
        widgets = {
            'hand': forms.RadioSelect,
            'slant': forms.RadioSelect,
            'transition': forms.RadioSelect,
            'please': forms.RadioSelect,
            'instruction': forms.RadioSelect,
            'material': forms.RadioSelect,
            'peer': forms.RadioSelect,
        }

scoreit/views.py
from django.shortcuts import render
from brain.models import StudentRoster, CurrentClass, Teacher, Schedule, Subject
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Score, TeacherApproval
from .forms import ScoreForm
import datetime
from django.utils.timezone import now, timedelta
from brain.templatetags.brain_extras import add_total_score
from variables import SUBJECTDICT, STYLEDICT


def class_list(request, student_id):
    # Get the Day
    date_object = datetime.date.today()
    day = date_object.strftime("%A")
    # Get student
    student = StudentRoster.objects.get(student_id=student_id)
    # Get student's teacher
    teacher = student.current_class.teacher
    # Get student's teacher's schedule for this day
    grade = student.current_class.grade
    try:
        schedule = Schedule.objects.get(teacher=teacher, day=day.upper())
    except:
        schedule = Schedule.objects.get(teacher=teacher, day="MONDAY")
    # Get list of all classes on this day in order
    classes = [schedule.subject1, schedule.subject2, schedule.subject3, schedule.subject4, schedule.subject5,
               schedule.subject6, schedule.subject7]
    classesandstyles = []
    for item in classes:  # Item = reading or writing
        # Find out if there is a score for the subject yet, and if so, put the score. Otherwise return None.
        icon, color = STYLEDICT[item.title]
        classesandstyles.append((item, icon, color))

    return render(request, 'scoreit/class_list.html', {'classesandstyles': classesandstyles, 'student': student,
                                                       'teacher': teacher, 'day': day, 'schedule': schedule,

                                                       'grade': grade, 'date': date_object,
                                                       })


def log_subject(request, student_id, subject):
    '''For this I need to have the different criteria in order for that subject. At the top it will say "CHANZE'S SPANISH SCORE IT"
    and it'll have the criteria with yes/no going down, with a submit button at the bottom. If they have already submitted the form
    it will be the same scores from before. If this is the first time, they will get a blank form where they have to click yes/no
    When they hit submit, it either creates or updates the form. '''
    # Get the Day
    date_object = now()
    day = date_object.strftime("%A")
    # Get student
    student = StudentRoster.objects.get(student_id=student_id)
    subjectobj = Subject.objects.get(title=subject)
    descriptions = SUBJECTDICT[subject]
    obj, created = Score.objects.get_or_create(student=student, date=date_object, subject=subjectobj)

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ScoreForm(request.POST, instance=obj)
        score = form.save(commit=False)
        score.subject = subjectobj
        score.student = student
        score.date = date_object
        score.save()
        messages.add_message(request, messages.SUCCESS,
                             "{} score saved!".format(subject))
        return HttpResponseRedirect(score.get_absolute_url())

    # if a GET (or any other method) we'll create a blank form
    else:
        # Check to see if the student/subject/date object already exists. If so, get that data. Otherwise new form
        form = ScoreForm(instance=obj)

    return render(request, 'scoreit/log_subject.html', {
        'student_id': student_id, 'student': student,
        'subject': subject, 'form': form, 'descriptions': descriptions
    })


def grade_view(request):
    teacher_list = ["Trost", "Cyphers", "Mackinnon"]
    date_object = now() - timedelta(hours=5)
    day_of_week = date_object.strftime("%A")
    weekend = ['SATURDAY', 'SUNDAY']
    if day_of_week.upper() in weekend:
        day_of_week = "Friday"
    teacher_student_list = []
    for teacher in teacher_list:
        teacherobj = Teacher.objects.get(last_name=teacher)
        schedule = Schedule.objects.get(teacher=teacherobj, day=day_of_week.upper())

        classes = [schedule.subject1, schedule.subject2, schedule.subject3, schedule.subject4, schedule.subject5,
                   schedule.subject6, schedule.subject7]
        student_list = StudentRoster.objects.filter(current_class__teacher__last_name=teacher).order_by('first_name')
        teacher_student_list.append((teacher,student_list, classes))

    return render(request, 'scoreit/grade_view.html', {
        'teacher_student_list':teacher_student_list, 'date':date_object,
    })

def grade_view_yesterday(request):
    teacher_list = ["Trost", "Cyphers", "Mackinnon"]
    date_object = now() - timedelta(days=1) - timedelta(hours=5)
    day_of_week = date_object.strftime("%A")
    teacher_student_list = []
    for teacher in teacher_list:
        teacherobj = Teacher.objects.get(last_name=teacher)
        schedule = Schedule.objects.get(teacher=teacherobj, day=day_of_week.upper())

        classes = [schedule.subject1, schedule.subject2, schedule.subject3, schedule.subject4, schedule.subject5,
                   schedule.subject6, schedule.subject7]
        student_list = StudentRoster.objects.filter(current_class__teacher__last_name=teacher).order_by('first_name')
        teacher_student_list.append((teacher,student_list, classes))

    return render(request, 'scoreit/grade_view.html', {
        'teacher_student_list':teacher_student_list, 'date':date_object,
    })

def grade_view_twodays(request):
    teacher_list = ["Trost", "Cyphers", "Mackinnon"]
    date_object = now() - timedelta(days=2) - timedelta(hours=5)
    day_of_week = date_object.strftime("%A")
    teacher_student_list = []
    for teacher in teacher_list:
        teacherobj = Teacher.objects.get(last_name=teacher)
        schedule = Schedule.objects.get(teacher=teacherobj, day=day_of_week.upper())

        classes = [schedule.subject1, schedule.subject2, schedule.subject3, schedule.subject4, schedule.subject5,
                   schedule.subject6, schedule.subject7]
        student_list = StudentRoster.objects.filter(current_class__teacher__last_name=teacher).order_by('first_name')
        teacher_student_list.append((teacher,student_list, classes))

    return render(request, 'scoreit/grade_view.html', {
        'teacher_student_list':teacher_student_list, 'date':date_object,
    })
def grade_view_threedays(request):
    teacher_list = ["Trost", "Cyphers", "Mackinnon"]
    date_object = now() - timedelta(days=3) - timedelta(hours=5)
    day_of_week = date_object.strftime("%A")
    teacher_student_list = []
    for teacher in teacher_list:
        teacherobj = Teacher.objects.get(last_name=teacher)
        schedule = Schedule.objects.get(teacher=teacherobj, day=day_of_week.upper())

        classes = [schedule.subject1, schedule.subject2, schedule.subject3, schedule.subject4, schedule.subject5,
                   schedule.subject6, schedule.subject7]
        student_list = StudentRoster.objects.filter(current_class__teacher__last_name=teacher).order_by('first_name')
        teacher_student_list.append((teacher,student_list, classes))

    return render(request, 'scoreit/grade_view.html', {
        'teacher_student_list':teacher_student_list, 'date':date_object,
    })

templates/scoreit/class_list.html
{% extends "brain/portal_layout.html" %}
{% load brain_extras %}
{% block title %}{{ student.first_name }} {{ student.last_name.0 }}'s Score It! | BTWA Portal {% endblock title %}
{% block heading %}
    <h1 style="margin-bottom: -0.5rem; text-align: center;">{{ student.first_name }} {{ student.last_name.0 }}'s Score It! </h1>
  <h5 style="text-align: center;"><a href="{% url 'brain:portalstudent' grade teacher.last_name student.student_id  %}"><i class="fa fa-arrow-circle-left"></i>  Back to my page</a></h5>

{% endblock heading %}
{% block content %}
<br>
 <div class="row">
            <div class="large-4 small-0 columns"> <br></div>
            <div class="large-4 small-12 columns">
            <table>
{% for item in classesandstyles %}
    {% with item.0 as subject %}
        {% with item.1 as icon %}
            {% with item.2 as color %}
<tr>
    <td style="padding: 0"> <a style="background-color: {{ color }}" href="{% url 'scoreit:logsubject' student.student_id subject %}" class="expanded button">
        <h6 style="margin: 0; font-size: 1.5em;"><i class="fa fa-{{ icon }}"></i>  {{ subject }}</h6></a></td>
<td >
    <h6>= {% add_subject_score student.student_id date subject %}</h6></td>
</tr>
            {% endwith %}    {% endwith %}
    {% endwith %}
    {% endfor %}
            </table>
      </div>
            <div class="large-4 small-0 columns"> <br></div>
             </div>
    <h3 style="text-align: center">Total Score: {% add_total_score student.student_id date %}</h3>

{% endblock content %}

templates/scoreit/grade_view.html
{% extends "brain/portal_layout.html" %}
{% load brain_extras %}
{% block title %}Score It Grade View | BTWA Portal {% endblock title %}
{% block heading %}

{% endblock heading %}
{% block content %}
<br>
 <div class="row">
            <div class="large-4 small-0 columns"> <br></div>

        Scores for date: {{ date }}
        {% for item in teacher_student_list %}
        {% with item.0 as teacher %}
        {% with item.1 as student_list %}
        <h2>{{ teacher }}</h2>
<table style="width: 350px">
{% with item.2 as classes %}
<tr>
<th>Student</th>
{% for class in classes %}
    <th>{{ class }}</th>
{% endfor %}
<th>Total</th>
</tr>

            {% for student in student_list %}
                {% with item.2 as classes %}
<tr>
    <td>{{ student.first_name }} {{ student.last_name.0 }}.</td>
    {% for class in classes %}
    <td>{% add_subject_score student.student_id date class %}</td>
{% endfor %}
<td>{% add_total_score student.student_id date %}</td>
</tr>
                {% endwith %}
    {% endfor %}
            </table>
    {% endwith %}
{% endwith %} {% endwith %}
    {% endfor %}
 </div>


{% endblock content %}

templates/scoreit/log_subject.html
{% extends "brain/portal_layout.html" %}
{% load brain_extras %}
{% block title %}{{ student.first_name }} 's {{ subject }} Score It! | BTWA Portal {% endblock title %}
{% block heading %}
    <style>
td {border: solid  slategray 1px}
    table tbody th, table tbody td {padding: 0px; padding-left: 10px;
        font-size:1.3em;}
    label{font-size: 1em; color: #343434; font-weight: bold;}
    li {
        display: block;}
    ul {padding-top:3px;
        margin:0; }
</style>



    <h1 style="margin-bottom: -0.5rem; text-align: center">{{ student.first_name }} {{ student.last_name.0 }}'s {{ subject }} Score It!</h1>
    <h5 style="text-align: center"><a href="{% url 'scoreit:classlist' student_id %}"><i class="fa fa-arrow-circle-left"></i>  Go Back</a></h5>

{% endblock heading %}
{% block content %}
<form method="POST" action="">

<div class="row">
  <div class="large-1 columns"><br></div>
  <div class="large-10 columns">



<table>

<tr><td><img src="/static/images/scoreit-hand.png"></td>
    <td>


{{ descriptions.0 }}</td><td>
{{ form.hand }} </td>
    </tr><tr><td><img src="/static/images/scoreit-slant.png"></td>
    <td>
{{ descriptions.1 }}</td><td>
{{ form.slant }}</td>
   </tr><tr><td><img src="/static/images/scoreit-transition.png"></td>
    <td>
{{ descriptions.2 }}</td><td>
{{ form.transition }}</td>
    </tr><tr><td><img src="/static/images/scoreit-please.png"></td>
    <td>
    {{ descriptions.3 }}</td><td>
{{ form.please }}</td>
    </tr><tr><td><img src="/static/images/scoreit-instruction.png"></td>
    <td>
    {{ descriptions.4 }}</td><td>
{{ form.instruction }}</td>
    </tr><tr><td><img src="/static/images/scoreit-material.png"></td>
    <td>
    {{ descriptions.5 }}</td><td>
{{ form.material }}</td>
    </tr><tr><td><img src="/static/images/scoreit-peer.png"></td>
    <td>
    {{ descriptions.6 }}</td><td>
{{ form.peer }}</td>
    </tr>
</table>
{% csrf_token %}
      <input style="align-items: center" type="submit" class="large expanded button" value="Score It!" >
        </div>
  <div class="large-1 columns"><br></div>
    </div>

    </form>
{% endblock content %}